### ISSUE TITLE
Can't run evaluate() from llamaindex integration

### ISSUE THREAD

**Issue by ulyssebottello** [explodinggradients/ragas#111] opened 2023-09-01 17:49 UTC
Hello team 👋

When I try to reproduce your [llamaindex notebook](https://github.com/explodinggradients/ragas/blob/main/docs/integrations/llamaindex.ipynb), without modifying anything, I've got an error with:

`result = evaluate(query_engine, metrics, eval_questions, eval_answers)`

It says:

`TypeError: evaluate() takes 3 positional arguments but 4 were given`

Any idea on how to make it work? Thanks!

**Comment by jjmachan** [comment] 2023-09-06 18:08
Hey there @ulyssebottello, I really appreciate the time you took to raise this issue and my sincere apologies for the delay, I was on leave last week but I've just released v0.0.12 which has fixed this issue for you.

I would really appreciate it if you take a look and let me know if it works at your end as well :)

**Comment by ryyeung** [comment] 2023-09-07 03:21
@jjmachan 
I have the new version ragas 0.0.12 and I'm getting the same error.

result = evaluate(query_engine, metrics, eval_questions, eval_answers)
TypeError: evaluate() takes from 1 to 3 positional arguments but 4 were given

**Comment by jjmachan** [comment] 2023-09-07 04:03
ohh that is strange because it seems to work at my end, @ryyeung Could you share the entire stack trace, would really help figure out what is wrong

**Comment by ryyeung** [comment] 2023-09-07 04:06
I'm using the Llama Index Github Data Loader. Could that cause problems?

![Screenshot 2023-09-06 at 9 05 29 PM](https://github.com/explodinggradients/ragas/assets/97981608/4deff662-7054-4407-9230-897ed3565587)

**Comment by ryyeung** [comment] 2023-09-12 15:47
@jjmachan Any updates?

**Comment by jjmachan** [comment] 2023-09-13 18:21
apologies @ryyeung was not able to reproduce at my end. are you on discord? if yes can you give me your username or email id? we can do a bit more debugging there and try and fix it.

**Comment by ryyeung** [comment] 2023-09-13 23:17
@jjmachan No worries! Yes, I just joined. My username is: ryyeung

**Comment by jjmachan** [comment] 2023-09-15 20:11
closing this after having a wonderful debug session with @ryyeung!

**Closed by jjmachan** 2023-09-15 20:11 UTC

**Comment by ulyssebottello** [comment] 2023-09-17 16:47
Well done guys! @jjmachan @ryyeung 🤝

**Comment by herrmalte** [comment] 2023-11-28 07:39
I am having the same issue, how did you solve it? @jjmachan @ryyeung

I am running:
ragas==0.021
openai==1.3.5
llama-index==0.9.8.post1
langchain==0.0.341
