### ISSUE TITLE
Possible bug? context_<space>relevancy -> has space in between

### ISSUE THREAD

**Issue by stepkurniawan** [explodinggradients/ragas#141] opened 2023-09-16 22:28 UTC
Hi team, 

I'm new with RAGAS, however I found this : 
```

from ragas.metrics import faithfulness, answer_relevancy, context_relevancy, context_recall
from ragas.langchain import RagasEvaluatorChain

# make eval chains
eval_chains = {
    m.name: RagasEvaluatorChain(metric=m) 
    for m in [faithfulness, answer_relevancy, context_relevancy, context_recall]
}

for name, eval_chain in eval_chains.items():
    score_name = f"{name}_score"
    print(f"{score_name}: {eval_chain(result)[score_name]}")

```

using template code, i found that the score name for context_ relevancy -> it has space in between. Is it just me? 
![image](https://github.com/explodinggradients/ragas/assets/11275004/22d76ffc-7dae-4d6f-9ac8-6c353b0c383d)
(dont mind the len=3, i was using different code)

**Comment by jjmachan** [comment] 2023-09-18 12:50
Hey @stepkurniawan this definitely seems like a bug and I will be fixing this shortly

**Comment by stepkurniawan** [comment] 2023-09-18 19:03
could you also check the context_recall and context_precision please? :)

**Comment by jjmachan** [comment] 2023-09-20 13:57
@stepkurniawan which version or ragas are you using, I had fixed this previously and am not able to reproduce this now. Can you try updating ragas to the latest version and try again?

**Comment by stepkurniawan** [comment] 2023-09-20 16:06
Sorry, could you tell me how to check the Version and update the Version?  Best regards, Stephen Kurniawan Von: Jithin JamesGesendet: Wednesday, 20 September 2023 15:57An: explodinggradients/ragasCc: Stephen Kurniawan; MentionBetreff: Re: [explodinggradients/ragas] Possible bug? context_<space>relevancy -> has space in between (Issue ***@***.*** which version or ragas are you using, I had fixed this previously and am not able to reproduce this now. Can you try updating ragas to the latest version and try again?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jjmachan** [comment] 2023-09-22 10:39
```python
import ragas
ragas.__version__
```

and you can update it by running
```bash
pip install -U ragas
```

version should be 0.0.13 - 0.0.14

**Comment by jjmachan** [comment] 2023-09-26 06:28
closing this hoping that fixed it @stepkurniawan, if you are still running into the issue please feel free to reopen this, more than happy to help fix it :)

**Closed by jjmachan** 2023-09-26 06:28 UTC
